# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_aisaka age1ggdnnmq2pp8c7jjmvtva7ak39veedydzaxf6kqpftm8pqn8wefdqp3hke9
  - &server_akebi age182vx6gj2wc2hgcymu4yfzrntegskdy5vqv2gkguuygsd73ac6euqze6ngs
  - &admin_v00334 age163e0c75a9s8n662e0u68ue8xf0gdx99jyuyww3par2zqrnkwksdsu39ly7
creation_rules:
  - path_regex: aisaka/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_aisaka
  - path_regex: kanan/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_aisaka
  - path_regex: akebi/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_aisaka
      - *server_akebi
  - path_regex: v00334/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_v00334
